/**
 * THE CROSS-REPO SEAM: this suite's only contact with a body the120 actually
 * produced.
 *
 * The response contract of `GET /api/fp/progress` is DECLARED TWICE — as
 * `ProgressChild` in the120's `app/api/fp/progress/progress-rules.ts` and as
 * `WireChild` in `../flowBoard.ts` — and both declarations were written from the
 * same reading of the same header. Nothing in either repo's suite had ever seen
 * the other's bytes, so a field rename on the server was a silent `undefined` at
 * runtime on this board with every test in both suites green. That is the root
 * cause of a class of seam bugs, not one instance of it.
 *
 * `fixtures/progress-response.json` closes it. It is the EXACT success body the
 * route emits, generated by running the real `shapeProgress` over a
 * representative store.
 *
 * ── Regenerating it ──
 *   cd ../120-The120
 *   npx tsx scripts/gen-fp-progress-fixture.ts \
 *     > ../first-profit/src/screens/staff/__tests__/fixtures/progress-response.json
 * The generator is deterministic (fixed ids, fixed stamps, a fixed `now`), so a
 * regeneration with no contract change produces a byte-identical file. If this
 * suite fails after a regeneration, the wire shape moved — fix the client or the
 * server, never the fixture by hand.
 *
 * ── What is asserted, and why these things ──
 * Not a snapshot. A snapshot of the narrowing would pass just as happily on a
 * payload every field of which arrived `undefined`. These assert that the
 * narrowing ACCEPTED everything (zero rejections is the field-name check: a
 * renamed `username` or `index` REJECTS, a renamed anything-else silently
 * defaults), and then that the math derived from it comes out where the
 * generator's fixture says it should.
 */
import { describe, expect, it } from "vitest";

import { narrowProgress } from "../StaffWatchtower";
import { anonymousUnits, computeFlowRows, criterionWindow, normalizeCohort } from "../flowBoard";
import fixture from "./fixtures/progress-response.json";

/** The generator's fixed instant. Fixture stamps are offsets from it, so the
 *  board must be computed against it or every recency reads as ancient. */
const NOW = Date.parse("2026-08-05T12:00:00.000Z");
const DAY = 86400e3;

describe("the wire fixture — a body produced by the120's real shapeProgress", () => {
  it("is the success envelope the route emits, not a hand-written stand-in", () => {
    expect(fixture.ok).toBe(true);
    expect(Array.isArray(fixture.children)).toBe(true);
    expect(fixture.children.length).toBeGreaterThan(0);
  });

  it("narrows with ZERO rejections — every child, idea and business is readable", () => {
    const narrowed = narrowProgress(fixture);
    expect(narrowed).not.toBeNull();
    expect(narrowed!.rejectedChildren).toBe(0);
    expect(narrowed!.rejectedIdeas).toBe(0);
    expect(narrowed!.rejectedBusinesses).toBe(0);
    expect(narrowed!.response.children).toHaveLength(fixture.children.length);
  });

  it("EXERCISES every field of the contract — a fixture of nulls pins nothing", () => {
    const narrowed = narrowProgress(fixture)!;
    const ideas = narrowed.response.children.flatMap((child) => child.ideas);
    const businesses = narrowed.response.children.flatMap((child) => child.businesses);

    // Both id spellings, and an id-less idea (the `legacy-idea-{index}` mint).
    expect(ideas.some((idea) => idea.id !== null)).toBe(true);
    expect(ideas.some((idea) => idea.id === null)).toBe(true);
    // Legacy maps AND stable maps.
    expect(ideas.some((idea) => Object.keys(idea.done).length > 0)).toBe(true);
    expect(ideas.some((idea) => Object.keys(idea.doneByTask).length > 0)).toBe(true);
    expect(ideas.some((idea) => Object.keys(idea.doneAt).length > 0)).toBe(true);
    expect(ideas.some((idea) => Object.keys(idea.doneAtByTask).length > 0)).toBe(true);
    // Every boolean and every optional number, in BOTH states.
    expect(ideas.some((idea) => idea.recencyClamped)).toBe(true);
    expect(ideas.some((idea) => !idea.recencyClamped)).toBe(true);
    expect(ideas.some((idea) => idea.hasCompletionsOutsideRequest)).toBe(true);
    expect(ideas.some((idea) => idea.lastCompletionAt !== null)).toBe(true);
    expect(ideas.some((idea) => idea.lastCompletionAt === null)).toBe(true);
    // The timing-evidence number, and the case that makes it worth having: it
    // LAGS `lastCompletionAt` when the newest stamp is not a completion.
    expect(
      ideas.some(
        (idea) =>
          idea.lastCorroboratedCompletionAt !== null &&
          idea.lastCompletionAt !== null &&
          idea.lastCorroboratedCompletionAt < idea.lastCompletionAt,
      ),
    ).toBe(true);
    // Businesses: linked, archived, and dangling.
    expect(businesses.some((business) => business.archived)).toBe(true);
    expect(businesses.some((business) => !business.archived)).toBe(true);
    expect(businesses.some((business) => business.ideaId === "idea-c1")).toBe(true);
    expect(businesses.some((business) => business.ideaId === "no-such-idea")).toBe(true);
    // Per-child flags, both states.
    const children = narrowed.response.children;
    expect(children.some((child) => child.truncated)).toBe(true);
    expect(children.some((child) => child.docUnreadable)).toBe(true);
    expect(children.some((child) => !child.docUnreadable && child.ideas.length === 0)).toBe(true);
  });

  it("normalizes into the cohort the fixture's store describes", () => {
    const cohort = normalizeCohort(narrowProgress(fixture)!.response, NOW);
    // 6 children: ada, bo, cy, di, eve (never signed in), fi (unreadable doc).
    expect(cohort.childCount).toBe(6);
    expect(cohort.unreadableChildren).toBe(1); // fi
    expect(cohort.truncatedChildren).toBe(1); // di, whose business entry was dropped
    expect(cohort.childrenWithNoUnits).toBe(1); // eve
    expect(cohort.unitsWithCompletionsOutsideRequest).toBe(1); // ada's second idea
    // ada 2 + bo 3 (one a placeholder) + cy 1 idea and 1 DANGLING business
    // (its two linked businesses folded) + di 1 = 8.
    expect(cohort.units).toHaveLength(8);
    expect(cohort.units.filter((unit) => unit.origin === "business")).toHaveLength(1);
    expect(cohort.maxUnitsPerChild).toBe(3);
    expect(cohort.maxIdeaUnitsPerChild).toBe(3);
    // Usernames survive the wire exactly as stored — the drill-down matches on
    // them, so a trim or a case-fold anywhere in the seam is a wrong roster.
    expect([...new Set(cohort.units.map((unit) => unit.username))].sort()).toEqual([
      "ada.fp",
      "bo.fp",
      "cy.fp",
      "di.fp",
    ]);
  });

  it("folds a business's completions onto its idea, and an ARCHIVED one's too", () => {
    const cohort = normalizeCohort(narrowProgress(fixture)!.response, NOW);
    const cy = cohort.units.find((unit) => unit.username === "cy.fp" && unit.origin === "idea")!;
    expect(cy.completions.has("4.1.1")).toBe(true); // the live business
    expect(cy.completions.has("4.1.2")).toBe(true); // the ARCHIVED one still counts
    // …but the archived record's recency does not: the live business's stamp
    // (1 day) wins over the archived one's (2 days), and the idea's own newest
    // stamp is 80 days old.
    expect(cy.lastCompletionAt).toBe(NOW - 1 * DAY);
  });

  it("computes the board the fixture's store describes, for criterion 1.2", () => {
    const cohort = normalizeCohort(narrowProgress(fixture)!.response, NOW);
    const window = criterionWindow("sell", "1.2");
    const rows = computeFlowRows(anonymousUnits(cohort), window, NOW);
    const rowBy = (taskId: string) => rows.find((row) => row.taskId === taskId)!;

    // Through 1.2.1: ada's two ideas, bo's legacy-keyed idea (1.2#0 remaps),
    // cy, and di. Five.
    expect(rowBy("1.2.1").throughput).toBe(5);
    // Through 1.2.2: ada's second idea and cy. Two.
    expect(rowBy("1.2.2").throughput).toBe(2);
    // ada's first idea is 5 days → 3 days on 1.2.1; bo's legacy pair is 9 → 6
    // days; cy is 90 → 88 days. Per-child medians [2, 3, 2] → 2 days.
    expect(rowBy("1.2.1").sampleChildCount).toBe(3);
    expect(rowBy("1.2.1").cycleTimeMedianMs).toBe(2 * DAY);
    // di's unit was CLAMPED, so it contributes no timing anywhere and is
    // counted as a dropped sample on the task it sits on.
    const di = cohort.units.find((unit) => unit.username === "di.fp")!;
    expect(di.recencyClamped).toBe(true);
    expect(rowBy("1.2.1").droppedSamples).toBe(1);
    // …and a clamped record's recency is not evidence either: the newest thing
    // on it is a bare stamp, so it reads uncorroborated rather than "just now".
    expect(di.recencyCorroborated).toBe(false);
    expect(cohort.unitsWithUncorroboratedRecency).toBe(1);
  });
});
